version: '3'

networks:
  default:
    external:
      name: main

services:
  nginx-proxy:
    image: nginx:mainline-alpine
    container_name: nginx-proxy
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./conf.d:/etc/nginx/conf.d
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    ports:
      - 80:80
      - 443:443
    restart: always

  docker-gen:
    image: jwilder/docker-gen
    container_name: docker-gen
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./docker-gen:/etc/docker-gen/templates
      # volumes_from is not available in v3, global volumes are not convenient, mounting manually
      - ./certs:/etc/nginx/certs:ro
      - ./conf.d:/etc/nginx/conf.d
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    command: -notify-sighup nginx-proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    restart: always

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs:rw
      # volumes_from is not available in v3, global volumes are not convenient, mounting manually
      - ./conf.d:/etc/nginx/conf.d
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
      NGINX_DOCKER_GEN_CONTAINER: docker-gen
      DEFAULT_EMAIL: your@email.com
    restart: always
