services:
  openconnect:
    image: openconnect:latest
    container_name: openconnect
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - ./openconnect.conf:/usr/local/etc/openconnect/openconnect.conf
