version: '3'
services:
  openvpn-3proxy:
    image: openvpn-3proxy
    container_name: openvpn-3proxy
    volumes:
      - ./openvpn/:/etc/openvpn
      - ./3proxy/3proxy.cfg:/etc/3proxy.cfg
    ports:
      - 1194:1194/udp
    cap_add:
      - NET_ADMIN
    restart: always
